// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjAtgN6psR92uCZgntj8yFUnRzJHy_D-8',
    appId: '1:560974513302:web:0321844149730a45d2eeb7',
    messagingSenderId: '560974513302',
    projectId: 'fitness-7584e',
    authDomain: 'fitness-7584e.firebaseapp.com',
    storageBucket: 'fitness-7584e.firebasestorage.app',
    measurementId: 'G-X1Q4N8GP4N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs6wIIYBXuPEkjrGXTX8xwuuGrsm_BFRE',
    appId: '1:560974513302:android:3b3a63a0782acb91d2eeb7',
    messagingSenderId: '560974513302',
    projectId: 'fitness-7584e',
    storageBucket: 'fitness-7584e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6oD85eHL3PHjIEcpW7Vcym1PE3VI7xB8',
    appId: '1:560974513302:ios:43a587473b098c79d2eeb7',
    messagingSenderId: '560974513302',
    projectId: 'fitness-7584e',
    storageBucket: 'fitness-7584e.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6oD85eHL3PHjIEcpW7Vcym1PE3VI7xB8',
    appId: '1:560974513302:ios:43a587473b098c79d2eeb7',
    messagingSenderId: '560974513302',
    projectId: 'fitness-7584e',
    storageBucket: 'fitness-7584e.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjAtgN6psR92uCZgntj8yFUnRzJHy_D-8',
    appId: '1:560974513302:web:2f3420b756de898fd2eeb7',
    messagingSenderId: '560974513302',
    projectId: 'fitness-7584e',
    authDomain: 'fitness-7584e.firebaseapp.com',
    storageBucket: 'fitness-7584e.firebasestorage.app',
    measurementId: 'G-BGNCTS4ZP5',
  );

}